### ISSUE TITLE
Crash on current frontpage

### ISSUE THREAD

**Issue by mtricht** [SimonHalvdansson/Harmonic-HN#6]
Stacktrace is:

```
FATAL EXCEPTION: main
Process: com.simon.harmonichackernews, PID: 8095
java.lang.IndexOutOfBoundsException: setSpan (50 ... 51) ends beyond length 50
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1326)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:685)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
	at com.simon.harmonichackernews.l.h(SourceFile:312)
	at androidx.recyclerview.widget.RecyclerView$s.i(SourceFile:1226)
	at androidx.recyclerview.widget.m.c(SourceFile:46)
	at androidx.recyclerview.widget.m.b(SourceFile:187)
	at androidx.recyclerview.widget.m.run(SourceFile:78)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by st1led** [comment]
If it helps debugging, it seems to happen only on the "Top Stories" tab and only when scrolling down.

Cleaning data / clearing the cache doesn't help.

**Comment by arubenis** [comment]
It looks like there is an issue with rendering this entry:
![image](https://github.com/SimonHalvdansson/Harmonic-HN/assets/8384419/5b2974be-04ff-4fcb-bbfd-c50540f510a4)

You can recreate it by searching this entry with text "Personal view", as soon as it tries to display it, the app craches

**Comment by SimonHalvdansson** [comment]
Thank you for providing the post which caused the error. The cause i the double space after complexity which confused a parser. A fix is coming now and it'll be deployed to Google Play immediately.
